services:
  feast:
    build:
      dockerfile: Dockerfile
    ports:
      - "6566-6581:6566"
    deploy:
      replicas: 16
    links:
      - redis
#  redis:
#    image: redis
#    ports:
#      - "6379:6379"
  redis:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data
volumes:
  dragonflydata:
