services:
  feast:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "6566-6581:6566"
    deploy:
      replicas: 16
    links:
      - redis
  redis:
    image: redis
