version: "3.9" 
services:
  feature-server:
    image: gcr.io/kf-feast/feature-server-java:develop
    ports:
      - "6566:6566"
    volumes:
      - ./config:/etc/feast
      - ../feature_repo/data:/data
    command:
      - java
      - -jar
      - /opt/feast/feast-serving.jar
      - --spring.config.location=classpath:/application.yml,file:/etc/feast/application-overrides.yaml
    links:
      - redis
  redis:
    image: redis
    ports:
      - "16379:6379"