services:
  feast:
    build:
      context: ../..
      dockerfile: docker/dynamo/Dockerfile
    ports:
      - "6566-6581:6566"
    deploy:
      replicas: 16
    volumes:
      - type: bind
        source: ${HOME}/.aws/
        target: /root/.aws
        read_only: yes
