services:
  feast:
    build:
      context: ../..
      dockerfile: docker/dynamo/Dockerfile
    ports:
      - "6566-6581:6566"
    deploy:
      replicas: 16
    volumes:
      - ~/.aws:/root/.aws:ro
