services:
  feast:
    build:
      context: ../..
      dockerfile: docker/datastore/Dockerfile
    ports:
      - "6566-6581:6566"
    deploy:
      replicas: 16
    volumes:
      - type: bind
        source: ${HOME}/.config/gcloud
        target: /root/.config/gcloud
